[package]
name = "kamilglapinskipoczta/dawid-domzal-website"
version = "0.2.0"
description = "Strona wizytówka Dawid Domżał - usługi geodezyjne Kalisz"

[dependencies]
"wasmer/static-web-server" = "1"

[fs]
public = "dist"
